#!/bin/sh
application_source="github地址"

## chang here
SERVICE_DIR=/var/www/ctoedu
SERVICE_NAME=blog-api-boot-jpa-data-0.0.1-SNAPSHOT
SPRING_PROFILES_ACTIVE=dev

## java env
export JAVA_HOME=/opt/jdk1.8
export JRE_HOME=${JAVA_HOME}/jre
start(){
		procedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
		if [ "${procedure}" = "" ];
		then
			echo "start ..."
			if [ "$2" != "" ];
			then
				SPRING_PROFILES_ACTIVE=$2
			fi
			echo "spring.profiles.active=${SPRING_PROFILES_ACTIVE}"
			exec nohup ${JRE_HOME}/bin/java -Xms128m -Xmx512m -jar ${SERVICE_DIR}/${SERVICE_NAME}\.jar --spring.profiles.active=${SPRING_PROFILES_ACTIVE} >/dev/null 2>&1 &
			echo "start success"
		else
			echo "${SERVICE_NAME} is start"
		fi
}

stop(){
		procedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
		if [ "${procedure}" = "" ];
		then
			echo "${SERVICE_NAME} is stop"
		else
			kill -9 ${procedure}
			sleep 1
			argprocedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
			if [ "${argprocedure}" = "" ];
			then
				echo "${SERVICE_NAME} stop success"
			else
				kill -9 ${argprocedure}
				echo "${SERVICE_NAME} stop error"
			fi
		fi
}

package(){
    profile=${1:-demo}
	tag=${2:-trunk}

	case $tag in
		trunk)
			svn sw $application_source/trunk/server .
		;;
		*)
			svn sw $application_source/tags/$tag/server .
		;;
	esac

	svn info > svn.info
	mvn clean package assembly:assembly -P$profile
}


case "$1" in

	restart)
		$0 stop
		sleep 1
		$0 start $2
	;;
	*)
		echo "usage: $0 [start|stop|restart] [dev|test|prod]"
	;;
esac
