#!/bin/sh
application_source="https://github.com/sen588/BLOG.git"

## chang here
SERVICE_DIR_TAG=/opt/applications/blog
SPRING_PROFILES_ACTIVE=dev

## java env
export JAVA_HOME=/usr/java/jdk1.8.0_251
export JRE_HOME=${JAVA_HOME}/jre
start(){
        SERVICE_NAME=${1:-test};
		procedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
		if [ "${procedure}" = "" ];
		then
			echo "start ..."
			if [ "$2" != "" ];
			then
				SPRING_PROFILES_ACTIVE=$2
			fi
			echo "spring.profiles.active=${SPRING_PROFILES_ACTIVE}"
			exec nohup ${JRE_HOME}/bin/java -Xms128m -Xmx512m -jar ${SERVICE_DIR_TAG}/${SERVICE_NAME}\.jar --spring.profiles.active=${SPRING_PROFILES_ACTIVE} >/dev/null 2>&1 &
			echo "start success"
		else
			echo "${SERVICE_NAME} is start"
		fi
}

stop(){
	    SERVICE_NAME=${1:-test};
		procedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
		if [ "${procedure}" = "" ];
		then
			echo "${SERVICE_NAME} is stop"
		else
			kill -9 ${procedure}
			sleep 1
			argprocedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
			if [ "${argprocedure}" = "" ];
			then
				echo "${SERVICE_NAME} stop success"
			else
				kill -9 ${argprocedure}
				echo "${SERVICE_NAME} stop error"
			fi
		fi
}

package(){
    profile=${1:-dev}
	tag=${2:-trunk}
	bs=${3:-server}

    git clone --branch ${tag} ${application_source} ${SERVICE_DIR_TAG}/${tag}
    cd ${SERVICE_DIR_TAG}/bs_blog_${bs}
    mvn clean package
    cd ${SERVICE_DIR_TAG}
    cp -a ${SERVICE_DIR_TAG}/bs_blog_${bs}/target/${bs}-${tag}.jar
}

case "$1" in

	start)
		start $args
	;;

	stop)
		stop  $args
	;;

	restart)
		stop  $args
		sleep 1m
		start $args
	;;

	package)
        package $args $1 $2
    ;;


    deploy)
        stop    $1
        package $1 $2

        cd      $SERVICE_DIR_TAG
        start   $1
    ;;

    batch)
        i=2
        while [ ! -d "$i" ]
        do
            stop    $1
            package $1 $i

            cd      $SERVICE_DIR_TAG
            start   $1
            i++
        done
    ;;

	*)
		echo "start---->启动服务------>命令格式:[start profile]"
        echo "stop----->停止服务------>命令格式:[stop profile]"
        echo "restart-->重启服务------>命令格式:[restart profile]"
        echo "package-->更新打包------>命令格式:[package profile tag]---------->创建安装包:[`pwd`/target/$application_name.tar.gz]"
        echo "install-->安装服务------>命令格式:[install]-------------->安装至:[$SERVICE_DIR_TAG]"
        echo "deploy--->安装重启------>命令格式:[deploy profile tag]--->如果tag为空,那么使用trunk下源码打包启动"
    ;;
esac
