#!/bin/sh
application_source="https://github.com/sen588/BLOG.git"

## chang here
SERVICE_DIR_TAG=/opt/project/jar
SPRING_PROFILES_ACTIVE=dev

## java env
export JAVA_HOME=/usr/java/jdk1.8.0_251
export JRE_HOME=${JAVA_HOME}/jre
start(){
        SERVICE_NAME=${1};
		procedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
		if [ "${procedure}" = "" ];
		then
			echo "start ..."
			nohup java -jar ${SERVICE_DIR_TAG}/${SERVICE_NAME}.jar &
			echo "start success"
		else
			echo "${SERVICE_NAME} is start"
		fi
}

stop(){
	    SERVICE_NAME=${1};
		procedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
		if [ "${procedure}" = "" ];
		then
			echo "${SERVICE_NAME} is stop"
		else
			kill -9 ${procedure}
			sleep 1
			argprocedure=`ps -ef | grep -w "${SERVICE_NAME}" |grep -w "java"| grep -v "grep" | awk '{print $2}'`
			if [ "${argprocedure}" = "" ];
			then
				echo "${SERVICE_NAME} stop success"
			else
				kill -9 ${argprocedure}
				echo "${SERVICE_NAME} stop error"
			fi
		fi
}

package(){
    profile=${1}
	tag=${2}
	bs=${3}

    cd ${SERVICE_DIR_TAG}/tag/bs_blog_${bs}
    mvn clean package
    rm -rf ${SERVICE_DIR_TAG}/${bs}.jar
    mv ${SERVICE_DIR_TAG}/tag/bs_blog_${bs}/target/${bs}.jar ${SERVICE_DIR_TAG}

}

pull(){
    tag=${1}

    git clone --branch ${tag} ${application_source} ${SERVICE_DIR_TAG}/tag
}

remover(){
    rm -rf ${SERVICE_DIR_TAG}/tag
}

case "$1" in

	start)
		start $args
	;;

	stop)
		stop  $1
	;;

	restart)
		stop  $args
		sleep 1m
		start $args
	;;

	package)
	    remover $args
	    pull    $2
        package $1 $2 $3
        remover $args
    ;;

    deploy)
        stop    $1
        package $1 $2

        cd      ${SERVICE_DIR_TAG}
        start   $1
    ;;

    batch)
        remover $args
        pull    $2
        a=0
        for i in $@
        do
           ((a++))
           if (( a>2 )); then
               package $1 $2 $i
               start   $i
           fi
        done
        remover $args
    ;;

	*)
		echo "start---->启动服务------>命令格式:[start profile]"
        echo "stop----->停止服务------>命令格式:[stop profile]"
        echo "restart-->重启服务------>命令格式:[restart profile]"
        echo "package-->更新打包------>命令格式:[package profile tag]---------->创建安装包:[`pwd`/target/$application_name.tar.gz]"
        echo "install-->安装服务------>命令格式:[install]-------------->安装至:[$SERVICE_DIR_TAG]"
        echo "deploy--->安装重启------>命令格式:[deploy profile tag]--->如果tag为空,那么使用trunk下源码打包启动"
    ;;
esac
